export const SECTIONS = [
  {
    id: 1,
    path: 'piso-6',
    name: 'Piso 6',
    description: 'Accede al sexto piso y explora sus instalaciones premium.',
    color: '#FF416C',
    gradient: 'linear-gradient(135deg, #FF4B2B 0%, #FF416C 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 2,
    path: 'piso-5',
    name: 'Piso 5',
    description: 'El quinto piso alberga espacios de trabajo colaborativo de alto rendimiento.',
    color: '#8A2387',
    gradient: 'linear-gradient(135deg, #E94057 0%, #8A2387 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 3,
    path: 'piso-4',
    name: 'Piso 4',
    description: 'Tecnología de vanguardia y diseño moderno definen el cuarto piso.',
    color: '#00B4DB',
    gradient: 'linear-gradient(135deg, #0083B0 0%, #00B4DB 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 4,
    path: 'piso-3',
    name: 'Piso 3',
    description: 'Integración perfecta y rendimiento inigualable en el tercer piso.',
    color: '#b20a2c',
    gradient: 'linear-gradient(135deg, #fffbd5 0%, #b20a2c 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 5,
    path: 'piso-2',
    name: 'Piso 2',
    description: 'El segundo piso combina accesibilidad y funcionalidad de primer nivel.',
    color: '#1D976C',
    gradient: 'linear-gradient(135deg, #93F9B9 0%, #1D976C 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 6,
    path: 'piso-1',
    name: 'Piso 1',
    description: 'La planta baja: el punto de encuentro y bienvenida del edificio.',
    color: '#F09819',
    gradient: 'linear-gradient(135deg, #EDDE5D 0%, #F09819 100%)',
    requiresAccess: true,
    hasTwoColumns: true,
    columns: [
      { label: 'Ala Norte', subPath: 'ala-norte' },
      { label: 'Ala Sur', subPath: 'ala-sur' },
    ],
  },
  {
    id: 7,
    path: 'parqueadero',
    name: 'Parqueadero',
    description: 'Gestión y acceso directo al área de estacionamiento del edificio.',
    color: '#7b4397',
    gradient: 'linear-gradient(135deg, #dc2430 0%, #7b4397 100%)',
    requiresAccess: false,
    hasTwoColumns: false,
  },
  {
    id: 8,
    path: 'seguridad',
    name: 'Seguridad',
    description: 'Centro de monitoreo y control de seguridad integral del edificio.',
    color: '#134E5E',
    gradient: 'linear-gradient(135deg, #71B280 0%, #134E5E 100%)',
    requiresAccess: false,
    hasTwoColumns: false,
  },
];
